### PR TITLE
add support for appveyor

### PR DESCRIPTION
**Pull request by vletoux**
add continuous integration for Windows like it is already available for OpenSC

### CODE REVIEW

**Comment by frankmorgner** [comment]
Thanks a lot for starting with Windows-CI! @nmav could you enable AppVeyor, please?

You made libp11 and OpenSSL optional for engine_pkcs11. I guess you only want to speed up things, but this makes users think that they could use the code without those dependencies. Please remove those configure switches. (same holds for https://github.com/OpenSC/libp11/pull/46 with its dependency to OpenSSL).

**Comment by vletoux** [comment]
just saw the git checkout from my own repository (which was needed for testing)
DO NOT COMMIT until the libp11 change has been accepted and that I fixed that.

**Comment by LudovicRousseau** [comment]
Is this PR ready to be merged now?

**Comment by vletoux** [comment]
working on it but you can add the appveyor project

**Comment by vletoux** [comment]
ok, the last appveyor build failed because it couldn't download the openssl setup.
(cache not active because it is a first build)
Except for that, everything went fine. My own repository built with success the project (see https://ci.appveyor.com/project/vletoux/engine-pkcs11)
I included the remarks from every people.
=> So yes, I think it could be merged.

Vincent

**Pull request merged**
