### PR TITLE
Various fixes and features

### PR DESCRIPTION
**Pull request by petrpisaratlascz**
As discussed on engine_pkcs11 mailing list, I'm offering my patch set for merging into engine_pkcs11 repository. See http://thread.gmane.org/gmane.comp.encryption.opensc.devel/14973 for more details.

### CODE REVIEW

**Comment by levitte** [comment]
Is there a reason why this pull request hasn't been merged yet, apart from the obvious need to rebase it?  I was going to make my own pull request with exactly the changes given in commit e901a88f9f466f2014c41f1d0e5c1da203ea6964 above, a change that is dearly needed (assuming anything about `callback_data` is just so damn wrong, outright dangerous!)

**Comment by dengert** [comment]
Well there is more interest in the engine and getting a release out. It has been 5 years, s now it the time to look at resubmitting. Since your pull request, Sept 2013, ECDSA and URIs for load_cert and load_key have been added. A rebase  of the changes would help move the process along. 

"Hexadecimal ID string contains colons" changes the user interface. Can you justify this?

"Decouple loging into the token" is doing a lot of pin caching, and it is not clear what is the problem it tries to solve. Can you give more justification?

The others appear to look reasonable.

**Comment by levitte** [comment]
I'll have you note that I'm not the original submitter, so I cannot answer your questions...

**Comment by gebi** [comment]
From my side i can only say that we really needed those patches as it was unusable otherwise. Memory leaks that in just a few hours kill the programm and segfaults left and right.
Especially the "Implement ENGINE_load_ssl_client_cert()" was really nice to have.
Thx @petrpisaratlascz for the patches, sad that they where not merged!

**Comment by petrpisaratlascz** [comment]
On Thu, Jul 16, 2015 at 02:45:15PM -0700, Doug Engert wrote:
> "Hexadecimal ID string contains colons" changes the user interface. Can you
> justify this?
> 
I don't remember. I think some tool printed the value with colons and so
simple cut-and-paste did not work. Also the hex_to_bin() supports it.  
If you don't like it, you can skip the patch. The PKCS#11 URI support should
make all these expressions obsolete.

> "Decouple loging into the token" is doing a lot of pin caching, and it is
> not clear what is the problem it tries to solve. Can you give more
> justification?
> 
Don't ask me. The caching was already there. The commit just moved it into
a separate function. Git blames Andreas Jellinghaus for the code. I have no
idea what software layer should do the caching. Maybe the "PIN retained"
comment will tell you more.

-- Petr

**Comment by petrpisaratlascz** [comment]
On Sat, Jul 25, 2015 at 04:29:01PM +0200, Petr Pisar wrote:
> On Thu, Jul 16, 2015 at 02:45:15PM -0700, Doug Engert wrote:
> > "Hexadecimal ID string contains colons" changes the user interface. Can you
> > justify this?
> > 
> I don't remember. I think some tool printed the value with colons and so
> simple cut-and-paste did not work.

I found it. p11tool prints object's ID with colons.

-- Petr

**Comment by petrpisaratlascz** [comment]
On Thu, Jul 16, 2015 at 02:45:15PM -0700, Doug Engert wrote:
> A rebase  of the changes would help move the process along. 
> 
I rebased the loadcert branch. I fixed few white spaces, a typo in a commit
message and I added two free_pin() calls in the "Free PIN storage where
needed" commit because of a code introduced by the new PKCS11 URI parser.

**Comment by dengert** [comment]
On 7/25/2015 3:40 PM, petrpisaratlascz wrote:
> On Sat, Jul 25, 2015 at 04:29:01PM +0200, Petr Pisar wrote:
>  > On Thu, Jul 16, 2015 at 02:45:15PM -0700, Doug Engert wrote:
>  > > "Hexadecimal ID string contains colons" changes the user interface. Can you
>  > > justify this?
>  > >
>  > I don't remember. I think some tool printed the value with colons and so
>  > simple cut-and-paste did not work.
>
> I found it. p11tool prints object's ID with colons.

p11tool is GnuTLS, not OpenSSL or OpenSC, so there is pressing reason to support this within OpenSC when used with the OpenSSL engine.

>
> -- Petr
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/engine_pkcs11/pull/5#issuecomment-124889195>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by nmav** [comment]
Given the support for PKCS #11 URLs in the current engine_pkcs11, how reasonable is the inclusion of the whole patch set? I don't think improving the old methods make sense in the view of that, however this patch set has some cleanups which are still relevant. Would it make sense to separate the pull requests with respect to functionality changes?

**Comment by petrpisaratlascz** [comment]
On Mon, Aug 24, 2015 at 01:50:59AM -0700, Nikos Mavrogiannopoulos wrote:
> Given the support for PKCS #11 URLs in the current engine_pkcs11, how
> reasonable is the inclusion of the whole patch set? I don't think improving
> the old methods make sense in the view of that, however this patch set has
> some cleanups which are still relevant. Would it make sense to separate the
> pull requests with respect to functionality changes?
> 
Last time when I rebased this patch set (2015-07-25), there was no libp11
release with PKCS#11 support. Did that changed? I wanted to test the URI
support in the engine_pkcs11, but I could not because of that. If I remember
correctly, there is an opened dispute with OpenSSL preventing from building
libp11 master code with PKCS#11 support.

In my humble opinion, until there is libp11 release with PKCS#11 support, it
does not make sense to remove support for the old methods.

Moreover I lost motivation to improve this patch set in any way. Upstream was
not able to merge any of my commits in last two years. And I don't think that
"git cherry-pick" all but the "Hexadecimal ID string contains colons" commit
is such a horrible load of work for the upstream to show some sign of
appreciation.

-- Petr

**Comment by nmav** [comment]
> Last time when I rebased this patch set (2015-07-25), there was no libp11
> release with PKCS#11 support. Did that changed? I wanted to test the URI
> support in the engine_pkcs11, but I could not because of that. If I remember
> correctly, there is an opened dispute with OpenSSL preventing from building
> libp11 master code with PKCS#11 support.

I believe you mean PKCS #11 URL support? In that case the PKCS #11 URL is directly in engine_pkcs11 not libp11.

> In my humble opinion, until there is libp11 release with PKCS#11 support, it
> does not make sense to remove support for the old methods.

It is not about removing that support, it is about whether spend any resources to improve it.

> Moreover I lost motivation to improve this patch set in any way. Upstream was
> not able to merge any of my commits in last two years.

I understand. There was no maintainer for these two project for very long time. I'll now attempt to make a release with bug fixes in libp11 and engine_pkcs11, and I'd appreciate if you could rebase and split the patches in bug fixes and new features for easier merge.

If it is about time let me know how much time you need and I'll delay the release.

**Comment by petrpisaratlascz** [comment]
On Tue, Aug 25, 2015 at 06:08:04AM -0700, Nikos Mavrogiannopoulos wrote:
> > Moreover I lost motivation to improve this patch set in any way. Upstream was
> > not able to merge any of my commits in last two years.
> 
> I understand. There was no maintainer for these two project for very long
> time. I'll now attempt to make a release with bug fixes in libp11 and
> engine_pkcs11, and I'd appreciate if you could rebase and split the patches
> in bug fixes and new features for easier merge.
> 
> If it is about time let me know how much time you need and I'll delay the
> release.
> 
I hope I will find a time next week to do it.

-- Petr

**Comment by petrpisaratlascz** [comment]
On Tue, Aug 25, 2015 at 06:08:04AM -0700, Nikos Mavrogiannopoulos wrote:
> > Last time when I rebased this patch set (2015-07-25), there was no libp11
> > release with PKCS#11 support. Did that changed? I wanted to test the URI
> > support in the engine_pkcs11, but I could not because of that. If I remember
> > correctly, there is an opened dispute with OpenSSL preventing from building
> > libp11 master code with PKCS#11 support.
> 
> I believe you mean PKCS #11 URL support? In that case the PKCS #11 URL is directly in engine_pkcs11 not libp11.
>

Indeed. Now it works despite this glitch:

If I build pkcs11_engine from master branch against libp11-0.2.8 and
openssl-1.0.2d, and I try to use the engine, OpenSSL and dynamic linker will
complain:

140020467279504:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(/home/petr/engine_pkcs11/src/.libs/engine_pkcs11.so): /home/petr/engine_pkcs11/src/.libs/engine_pkcs11.so: undefined symbol: PKCS11_get_ecdsa_method

The PKCS11_get_ecdsa_method symbol is not provided by libp11-0.2.8 which is
the latest release. But it exists in lib11 git master branch. I recommend to
add a configure-time check for libp11 version into the engine_pkcs11.

I tested the PKCS#11 URL with openssl tool and curl tool and a libcurl
application: openssl(1) loads certificates always from file, loading key works.
curl(1) truncates certificate identifier to "pkcs11", loading key works,
libcurl application can address both key and certificate.


> I understand. There was no maintainer for these two project for very long
> time. I'll now attempt to make a release with bug fixes in libp11 and
> engine_pkcs11, and I'd appreciate if you could rebase and split the patches
> in bug fixes and new features for easier merge.
> 
The fixes rebased on top of current master
(d00be94b277d4257795401bcec31fb0915216bfb) are in "fixonly" branch of
petrpisaratlascz/engine_pkcs11 repository, the new feature rebased on top of
it are in "ENGINE_load_ssl_client_cert" branch. I skipped the unpopular
"Hexadecimal ID string contains colons" commit.

If I figure out how to reference them in the web interface in this thread,
I will do it.

-- Petr

**Comment by dengert** [comment]
On 9/5/2015 1:31 PM, petrpisaratlascz wrote:
> On Tue, Aug 25, 2015 at 06:08:04AM -0700, Nikos Mavrogiannopoulos wrote:
>  > > Last time when I rebased this patch set (2015-07-25), there was no libp11
>  > > release with PKCS#11 support. Did that changed? I wanted to test the URI
>  > > support in the engine_pkcs11, but I could not because of that. If I remember
>  > > correctly, there is an opened dispute with OpenSSL preventing from building
>  > > libp11 master code with PKCS#11 support.
>  >
>  > I believe you mean PKCS #11 URL support? In that case the PKCS #11 URL is directly in engine_pkcs11 not libp11.
>  >
>
> Indeed. Now it works despite this glitch:
>
> If I build pkcs11_engine from master branch against libp11-0.2.8 and
> openssl-1.0.2d, and I try to use the engine, OpenSSL and dynamic linker will
> complain:
>
> 140020467279504:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(/home/petr/engine_pkcs11/src/.libs/engine_pkcs11.so):
> /home/petr/engine_pkcs11/src/.libs/engine_pkcs11.so: undefined symbol: PKCS11_get_ecdsa_method
>
> The PKCS11_get_ecdsa_method symbol is not provided by libp11-0.2.8 which is
> the latest release. But it exists in lib11 git master branch. I recommend to
> add a configure-time check for libp11 version into the engine_pkcs11.

How about a release of libp11 at the same time.

>
> I tested the PKCS#11 URL with openssl tool and curl tool and a libcurl
> application: openssl(1) loads certificates always from file, loading key works.
> curl(1) truncates certificate identifier to "pkcs11", loading key works,
> libcurl application can address both key and certificate.
>
>
>  > I understand. There was no maintainer for these two project for very long
>  > time. I'll now attempt to make a release with bug fixes in libp11 and
>  > engine_pkcs11, and I'd appreciate if you could rebase and split the patches
>  > in bug fixes and new features for easier merge.
>  >
> The fixes rebased on top of current master
> (d00be94b277d4257795401bcec31fb0915216bfb) are in "fixonly" branch of
> petrpisaratlascz/engine_pkcs11 repository, the new feature rebased on top of
> it are in "ENGINE_load_ssl_client_cert" branch. I skipped the unpopular
> "Hexadecimal ID string contains colons" commit.
>
> If I figure out how to reference them in the web interface in this thread,
> I will do it.
>
> -- Petr
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/engine_pkcs11/pull/5#issuecomment-137985145>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Pull request closed without merging**
